local paser = {};

paser.STREAM_TABLE =
{
	IGNORED = {"COMMENT","SPACE","HORIZONTAL_TAB","CARRIAGE_RETURN","LINE_FEED"},
	INVALID = {"INVALID_CHARACTER","INVALID_NUMBER","INVALID_STRING","INVALID_PUNCTUATION"},
	SCOPE =
	{
		["ROUTINE"] = {"GLOBAL","THREAD","LOCAL"},
		["CLASS"] = {"PUBLIC","PRETECTED","PRIVATE"}
	},
	MUTABILITY = {"CONSTANT","VARIABLE"},
	ASSIGNMENT =
	{
		INITIALIZATION = {"EQUAL","COLON-EQUAL"},
		EXPRESSION = {"EQUAL","PLUS-EQUAL","MINUS-EQUAL","ASTERISK-EQUAL","SLASH-EQUAL","PERCENT-EQUAL"}
	},
	EXPRESSION =
	{
		["INLINE"] =
		{
			"PARENTHESIS_OPEN","PARENTHESIS_CLOSE",
			"NULL","BOOLEAN","NUMBER","STRING","WORD",
			"NOT","AND","OR","XOR",
			"POSITIVE","NEGATIVE","PLUS","MINUS","ASTERISK","SLASH","PERCENT",
			"DOT",
			"LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"
		},
		["STATEMENT"] = {"EQUAL","PLUS-EQUAL","MINUS-EQUAL","ASTERISK-EQUAL","SLASH-EQUAL","PERCENT-EQUAL"},
		COMPOUND = {"ENTITY"}
	}
};

table.insert(paser.STREAM_TABLE.SCOPE["CLASS"],paser.STREAM_TABLE.SCOPE["ROUTINE"]);
table.insert(paser.STREAM_TABLE.EXPRESSION["STATEMENT"],paser.STREAM_TABLE.EXPRESSION["INLINE"]);

paser.FILTER_TABLE =
{
	["INLINE"] =
	{
		["PARENTHESIS_OPEN"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","NEGATIVE","POSITIVE","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["PARENTHESIS_CLOSE"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","ENTITY"},
		["NULL"] = {"START","PARENTHESIS_OPEN","DOUBLE-EQUAL","NOT-EQUAL"},
		["BOOLEAN"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","DOUBLE-EQUAL","NOT-EQUAL"},
		["NUMBER"] = {"START","PARENTHESIS_OPEN","NEGATIVE","POSITIVE","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["STRING"] = {"START","PARENTHESIS_OPEN","PLUS","DOUBLE-EQUAL","NOT-EQUAL"},
		["ENTITY"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","NEGATIVE","POSITIVE","PLUS","MINUS","ASTERISK","SLASH","PERCENT","DOT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["NOT"] = {"START","PARENTHESIS_OPEN","AND","OR","XOR","DOUBLE-EQUAL","NOT-EQUAL"},
		["AND"] = {"PARENTHESIS_CLOSE","BOOLEAN","ENTITY"},
		["OR"] = {"PARENTHESIS_CLOSE","BOOLEAN","ENTITY"},
		["XOR"] = {"PARENTHESIS_CLOSE","BOOLEAN","ENTITY",},
		["POSITIVE"] = {"START","PARENTHESIS_OPEN","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["NEGATIVE"] = {"START","PARENTHESIS_OPEN","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["PLUS"] = {"PARENTHESIS_CLOSE","NUMBER","STRING","ENTITY"},
		["MINUS"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY",},
		["ASTERISK"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["SLASH"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["PERCENT"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["DOT"] = {"ENTITY"},
		["LESS"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["LESS-EQUAL"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["DOUBLE-EQUAL"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","ENTITY"},
		["NOT-EQUAL"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","ENTITY"},
		["GREATER-EQUAL"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"},
		["GREATER"] = {"PARENTHESIS_CLOSE","NUMBER","ENTITY"}
	}
};

paser.RPN_TABLE =
{
	GROUP = {"PARENTHESIS_OPEN","PARENTHESIS_CLOSE"},
	OPERAND = {"NULL","BOOLEAN","NUMBER","STRING","ENTITY"},
	OPERATOR =
	{
		"EQUAL","EQUAL-PLUS","EQUAL-MINUS","EQUAL-ASTERISK","EQUAL-SLASH","EQUAL-PERCENT",
		"NOT","AND","OR","XOR",
		"POSITIVE","NEGATIVE","PLUS","MINUS","ASTERISK","SLASH","PERCENT",
		"DOT",
		"LESS","LESS-EQUAL","EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"
	}
};

paser.OPERATOR_TABLE =
{
	["DOT"] = {8,"LEFT"},
	["NOT"] = {7,"RIGHT"},
	["POSITIVE"] = {7,"RIGHT"},
	["NEGATIVE"] = {7,"RIGHT"},
	["ASTERISK"] = {6,"LEFT"},
	["SLASH"] = {6,"LEFT"},
	["PERCENT"] = {6,"LEFT"},
	["PLUS"] = {5,"LEFT"},
	["MINUS"] = {5,"LEFT"},
	["LESS"] = {4,"LEFT"},
	["LESS-EQUAL"] = {4,"LEFT"},
	["GREATER-EQUAL"] = {4,"LEFT"},
	["GREATER"] = {4,"LEFT"},
	["EQUAL"] = {3,"LEFT"},
	["NOT-EQUAL"] = {3,"LEFT"},
	["AND"] = {2,"LEFT"},
	["OR"] = {1,"LEFT"}
};
