local paser = {};

paser.STREAM_TABLE =
{
	IGNORABLE = {"COMMENT","SPACE","HORIZONTAL_TAB","CARRIAGE_RETURN","LINE_FEED"},
	INVALID = {"INVALID_CHARACTER","INVALID_NUMBER","INVALID_STRING","INVALID_PUNCTUATION"},
	SCOPE =
	{
		["ROUTINE"] = {"GLOBAL","THREAD","LOCAL"},
		["CLASS"] = {"PUBLIC","PRETECTED","PRIVATE"}
	},
	MUTABILITY = {"CONSTANT","VARIABLE"},
	ASSIGNMENT =
	{
		["INITIALIZATION"] = {"EQUAL","COLON-EQUAL"},
		["EXPRESSION"] = {"EQUAL","PLUS-EQUAL","MINUS-EQUAL","ASTERISK-EQUAL","SLASH-EQUAL","PERCENT-EQUAL"}
	},
	EXPRESSION =
	{
		["INLINE"] = {"PARENTHESIS_OPEN","PARENTHESIS_CLOSE","BRACKET_OPEN","BRACE_OPEN","NULL","BOOLEAN","NUMBER","STRING","FUNCTION","CLOSURE","CLASS","WORD","NOT","AND","OR","XOR","PLUS","MINUS","ASTERISK","SLASH","PERCENT","DOT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["STATEMENT"] = {"PARENTHESIS_OPEN","PARENTHESIS_CLOSE","BRACKET_OPEN","BRACE_OPEN","EQUAL","PLUS-EQUAL","MINUS-EQUAL","ASTERISK-EQUAL","SLASH-EQUAL","PERCENT-EQUAL","NULL","BOOLEAN","NUMBER","STRING","FUNCTION","CLOSURE","CLASS","WORD","NOT","AND","OR","XOR","PLUS","MINUS","ASTERISK","SLASH","PERCENT","DOT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["COMPOUND"] = {"INDEX","KEY","ARGUMENTS","ENTITY"},
		["OPERATOR"] = {"PLUS","MINUS","ASTERISK","SLASH","PERCENT","DOT"}
	}
};

paser.FILTER_TABLE =
{
	["INLINE"] =
	{
		["PARENTHESIS_OPEN"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["PARENTHESIS_CLOSE"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","INDEX","KEY","ARGUMENTS","ENTITY"},
		["NULL"] = {"START","PARENTHESIS_OPEN","DOUBLE-EQUAL","NOT-EQUAL"},
		["BOOLEAN"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","DOUBLE-EQUAL","NOT-EQUAL"},
		["NUMBER"] = {"START","PARENTHESIS_OPEN","PLUS","MINUS","ASTERISK","SLASH","PERCENT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["STRING"] = {"START","PARENTHESIS_OPEN","DOUBLE-EQUAL","NOT-EQUAL"},
		["LIST"] = {"START"},
		["MAP"] = {"START"},
		["FUNCTION"] = {"START"},
		["CLOUSURE"] = {"START"},
		["CLASS"] = {"START"},
		["INDEX"] = {"INDEX","KEY","ARGUMENTS","ENTITY"},
		["KEY"] = {"INDEX","KEY","ARGUMENTS","ENTITY"},
		["ARGUMENTS"] = {"INDEX","KEY","ARGUMENTS","ENTITY"},
		["ENTITY"] = {"START","PARENTHESIS_OPEN","NOT","AND","OR","XOR","PLUS","MINUS","ASTERISK","SLASH","PERCENT","DOT","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["NOT"] = {"START","PARENTHESIS_OPEN","AND","OR","XOR","DOUBLE-EQUAL","NOT-EQUAL"},
		["AND"] = {"PARENTHESIS_CLOSE","BOOLEAN","INDEX","KEY","ARGUMENTS","ENTITY"},
		["OR"] = {"PARENTHESIS_CLOSE","BOOLEAN","INDEX","KEY","ARGUMENTS","ENTITY"},
		["XOR"] = {"PARENTHESIS_CLOSE","BOOLEAN","INDEX","KEY","ARGUMENTS","ENTITY"},
		["NEGATIVE"] = {"START","PARENTHESIS_OPEN","ADDITION","SUBTRACTION","MULTIPLICATION","DIVISION","MODULO","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["POSITIVE"] = {"START","PARENTHESIS_OPEN","ADDITION","SUBTRACTION","MULTIPLICATION","DIVISION","MODULO","LESS","LESS-EQUAL","DOUBLE-EQUAL","NOT-EQUAL","GREATER-EQUAL","GREATER"},
		["ADDITION"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["SUBTRACTION"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["MULTIPLICATION"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["DIVISION"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["MODULO"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["INDEXATION"] = {"INDEX","KEY","ARGUMENTS","ENTITY"},
		["LESS"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["LESS-EQUAL"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["DOUBLE-EQUAL"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","INDEX","KEY","ARGUMENTS","ENTITY"},
		["NOT-EQUAL"] = {"PARENTHESIS_CLOSE","NULL","BOOLEAN","NUMBER","STRING","INDEX","KEY","ARGUMENTS","ENTITY"},
		["GREATER-EQUAL"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"},
		["GREATER"] = {"PARENTHESIS_CLOSE","NUMBER","INDEX","KEY","ARGUMENTS","ENTITY"}
	}
}
