local paser = {};

paser.STREAM_TABLE =
{
	IGNORABLE = {"COMMENT","SPACE","HORIZONTAL_TAB","CARRIAGE_RETURN","LINE_FEED"},
	INVALID = {"INVALID_NUMBER","INVALID_STRING","INVALID_PUNCTUATION","INVALID_CHARACTER"},
	SCOPE = {"GLOBAL","THREAD","LOCAL","PUBLIC","PRETECTED","PRIVATE"},
	MUTABILITY = {"CONSTANT","VARIABLE"},
	ASSIGNMENT = {"EQUAL","PLUS-EQUAL","MINUS-EQUAL","ASTERISK-EQUAL","SLASH-EQUAL","PERCENT-EQUAL","COLON-EQUAL"}
};
